### ISSUE TITLE
Hyphens in metadata column names passed to ancombc's --p-formula being interpreted as formulaically meaningful 

### ISSUE THREAD

**Issue by colinvwood** [qiime2/q2-composition#129]
It seems that when a user specifies a metadata column name that contains hyphens, e.g. `my-column` to the `--p-formula` option to `qiime composition ancombc`, the hyphens are interpreted as mathematical symbols and one term becomes two: `my` and `column`. Then the metadata key errors on `my`. This is happening [here](https://github.com/qiime2/q2-composition/blob/89c2a1c6d885134ab971627d289aa5685ad2febf/q2_composition/_ancombc.py#L57).

See forum post [here](https://forum.qiime2.org/t/ancombc-difficulty-with-column-headings-in-metadata/28114).

**Comment by lizgehret** [comment]
Hey @colinvwood just FYI there's already an open issue on this: https://github.com/qiime2/q2-composition/issues/100
