### ISSUE TITLE
DEP: ANCOMBC unable to load phyloseq

### ISSUE THREAD

**Issue by cherman2** [qiime2/q2-composition#135]
**Bug Description**
ruuning ancombc on QIIME2-metagenomics-2024.5  on Linux. 

Error: package or namespace load failed for ‘phyloseq’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/scratch/crh423/conda2/envs/qiime2-metagenome-2024.5/lib/R/library/ade4/libs/ade4.so':
  /scratch/crh423/conda2/envs/qiime2-metagenome-2024.5/lib/R/bin/exec/../../lib/../.././libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /scratch/crh423/conda2/envs/qiime2-metagenome-2024.5/lib/R/library/ade4/libs/ade4.so)

**Command**
qiime composition ancombc --i-table end-all-taxa-5-metaphlan-table-freq-filt.qza  --m-metadata-file ../../../metadata-current.tsv --p-formula  "Type"  --o-differentials type-diff

**Comments**
1. I was able to get this to work by switching to q2-metagenome-2024.2 
2. This error is not reproducible on MAC

**Screenshots**
<img width="576" alt="Screenshot 2024-07-19 at 1 11 43 PM" src="https://github.com/user-attachments/assets/b003fad5-9d4a-4f20-81f7-5890dfe107f4">

**Computation Environment**
- OS: Linux
- QIIME 2 Release QIIME2-metagenomics-2024.5

**Comment by ebolyen** [comment]
I'm able to reproduce this on my linux machine as well.

We've found that all of the library objects are loaded from within the conda environment, so it's not a case of escaping the env.

Rather it appears that there's an unknown-to-conda conflict in libcxx here. This will take some investigation into the original recipes.

**Comment by lizgehret** [comment]
forum xref: https://forum.qiime2.org/t/q2-composition-ancombc-error/31271

**Comment by lizgehret** [comment]
seems like it's just an issue with the linux environment file. @Oddant1 is testing on his machine today to confirm.

**Comment by lizgehret** [comment]
okay so this is a confirmed issue with the linux environment files for 2024.5 (both metagenome and amplicon are affected). @Oddant1 confirmed that creating a fresh environment from the 2024.5 seed environment resolved the issue, so I'm re-minting the 2024.5 environment files and we'll make sure that fixes the issue before merging.
