### ISSUE TITLE
IMP: da-barplot should use consistant colors for enriched/depleted

### ISSUE THREAD

**Issue by colinbrislawn** [qiime2/q2-composition#137]
**Improvement Description**
Make the color scheme consistent, even when all graphed features are only enriched or only depleted

**Current Behavior**
"enriched" and "depleted" are filled with in blue and orange, except when all features passing filter have the same sign, then they are all blue.  

**Proposed Behavior**
The color scheme should be consistent (🟦 & 🟧 or whatever), even when all results have the same sign.

>consistent with the other graphs in terms of color scheme for clarity 

**References**
forum x-ref: https://forum.qiime2.org/t/ancombc-barplot-colors/32082

**Comment by SergioAlias** [comment]
Hi! Not sure if this is the correct way of suggesting how to implement an improvement inside GitHub, but here I come:

I think this could be achieved making colors explicit when generating the Vega code.

Inside Layer -> Encoding -> Color, we can add the following:

```
"scale": {
  "domain": ["enriched", "depleted"],
  "range": ["blue", "orange"]
},
```
I'm not sure these orange and blue are the original tones though.

The forum x-ref mentioned in the OP contains an example of this.

**Comment by colinbrislawn** [comment]
>Not sure if this is the correct way ... but here I come

I like code suggestions in issues! 👍 
The other way is to fork the repo and open a PR. That's more work, but also more helpful!
~~(If that's something you want to try, this could be a good opportunity)~~
oh, you have made PRs before

**Comment by SergioAlias** [comment]
I may have some spare time this week so I'll try!
