### ISSUE TITLE
improvements to ancom qzv

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-composition#15]
**Improvement Description**
- [ ] title of page is _volcano plot_ - should be something else
- [ ] merge the two tables (conditionally, if they both exist)
- [ ] sort tables by W (if that makes sense to do)
- [ ] abundance table columns contain different numbers of digits (probably coming from pandas)

**Comment by lizgehret** [comment]
Discussed with @gregcaporaso - we are going to close anything ancom related in favor of maintaining and improving on ancombc and its associated visualizations.
