### ISSUE TITLE
improve ANCOM paired testing: add parameter for linking paired samples via metadata

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-composition#26]
**Current Behavior**
``ancom`` currently supports paired tests, e.g., with ``ttest_rel``, but it is currently a bit difficult to use (need to order samples in the sample metadata).

**Proposed Behavior**
It would be ideal to add a parameter that takes a user-defined metadata category (which should contain a "site name" or "subject id" type metadata that links paired samples) to automatically order samples for paired testing, when paired tests are selected.

**Comments**
I predict that a common error would arise from feature tables or mapping files that are missing paired samples (e.g., when the "subject id" column contains some singleton values or if a sample is missing from a feature table after abundance filtering). Instead of exiting with an error, it would be useful to ignore such samples, and instead print a message to stdout listing missing and unpaired samples.

**Comment by mortonjt** [comment]
Note that this is true for any repeated measures test, such as `friedmanchisquare`.

**Comment by gregcaporaso** [comment]
This would be really great to add. I'm going to be working on a plugin for doing paired difference testing, so ultimately it would be nice to match the relevant parameter naming, missing data handling, etc between these plugins.

**Comment by bhillmann** [comment]
Has this issue been implemented for paired-testing and merged?

**Comment by nbokulich** [comment]
@bhillmann no, it has not — if you are interested let us know. 

cc: @BenKaehler

**Comment by IrshadUlHaq1** [comment]
@nbokulich @bhillmann I am interested in paired-testing and would be thankful if it becomes available at some point.

**Comment by lizgehret** [comment]
Closing all ancom related issues as we will no longer be maintaining/improving ancom, and instead will focus on ancombc improvements moving forward (and ancombc2 once that paper has been published).
