### ISSUE TITLE
Remove duplicate type-format registration

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-composition#31]
[This isn't needed](
https://github.com/qiime2/q2-composition/blob/00f7df2c96bd2461c5ba4804b22bf035e0c70ddc/q2_composition/plugin_setup.py#L38-L41), but we used it in an early version of q2-types to keep the tests working (which this code is likely based on).

**Comment by mortonjt** [comment]
In what cases do you need the type-format registration?

**Comment by ebolyen** [comment]
It basically teaches a semantic-type how to store it's data in the `/data/` directory of an artifact. 

Right now it is our opinion that there should be only one canonical format at any given time. Once written, the format is stored in the artifact, so a chain of transformers can be invoked in the future in the event the registration changes.

**Comment by ebolyen** [comment]
Fixed in #34
