### ISSUE TITLE
Empty volcano plot

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-composition#43]
I'm not sure how this happens exactly, but we found a dataset where no features exceeded the `theta` threshold for the `W` score, and the volcano plot didn't show any points. The `ancom.csv` file looked fine, it was mostly 0s for the `W` score, but there were a handful of features that had `<30` scores.

**Comment by thermokarst** [comment]
This appears to happen when the `transform_function` produces `NaN` values:
```
                                                      W  sqrt
Unassigned;__;__;__;__;__                             8   NaN
k__Archaea;p__Crenarchaeota;c__Thaumarchaeota;o...   13   NaN
k__Archaea;p__Crenarchaeota;c__Thaumarchaeota;o...   10   NaN
k__Archaea;p__Euryarchaeota;c__Halobacteria;o__...    8   NaN
k__Archaea;p__Euryarchaeota;c__Methanobacteria;...   11   NaN
k__Archaea;p__Euryarchaeota;c__Methanobacteria;...   12   NaN
k__Archaea;p__Euryarchaeota;c__Methanomicrobia;...    8   NaN
k__Archaea;p__Euryarchaeota;c__Thermoplasmata;o...   12   NaN
k__Bacteria;__;__;__;__;__                            7   NaN
```

I haven't dug in too deep yet on how/why those values are present.
