### ISSUE TITLE
incorporate taxonomic information into ANCOM output

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-composition#47]
**Improvement Description**
Accept an optional `FeatureData[Taxonomy]` artifact. If input, add taxonomy metadata to features (and generates cladogram?).

Alternatively, add lefse visualizer to q2-composition?

Better yet, create a separate visualizer that takes a list of hierarchical features (e.g., significant features from ANCOM or other composition methods) and generates a lefse-like dendrogram.

**References**
[forum xref](https://forum.qiime2.org/t/incorporating-taxonomic-info-to-the-ancom-output/2174)

**Comment by ElDeveloper** [comment]
👍 this would be very useful.

**Comment by bigdoyle** [comment]
yes, please!

**Comment by lizgehret** [comment]
Closing all ancom related issues as we will no longer be maintaining/improving ancom, and instead will focus on ancombc improvements moving forward (and ancombc2 once that paper has been published).
