### ISSUE TITLE
update to ANCOM 2.0

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-composition#48]
**Improvement Description**
The first author of the ANCOM paper, @sidhujyatha, has shared some R code with me which he would like to get wrapped in a QIIME 2 plugin, so we can support the latest version of ANCOM (ANCOM 2.0). This would be great to get in place, but we just need someone to take on wrapping this R script in a QIIME 2 plugin.

**Comment by gregcaporaso** [comment]
@FrederickHuangLin is interested in working with us on this plugin, so we should follow up once we're ready to get this plugin updated.

**Comment by gregcaporaso** [comment]
I have an updated version of this R code now, which was emailed to me by @sidhujyatha on 16 Jan 2018.

**Comment by timyerg** [comment]
Hi! The latest Qiime2 release already updated to ANCOM-2.0?

**Comment by thermokarst** [comment]
Hi @timyerg, no, we have not yet added ANCOM 2 to this plugin.

**Comment by timyerg** [comment]
Thank you for the reply. I am @timanix, btw.
I downloaded the file for R you shared on the forum, but I am not sure that I can use it since it wasn't provided to me by the authors and I cannot find any website with the source and references...

**Comment by mestaki** [comment]
Hi @timyerg ,
> Thank you for the reply. I am @timanix, btw.
> I downloaded the file for R that Mehrbod_Estaki shared on the forum, but I am not sure that I can use it since it wasn't provided to me by the authors and I cannot find any website with the source and references...
A bit late to this part, but just for reference, the source code that I linked to on the forum comes from the author's (Dr. Mandal) [person page here](https://sites.google.com/site/siddharthamandal1985/research).

**Comment by lizgehret** [comment]
Circling back on this for posterity - closing out this PR since we are currently working on adding ANCOM-BC in place of adding ANCOM 2 into q2-composition. This should be released in the November 2022 update, so stay tuned!

[Development branch](https://github.com/qiime2/q2-composition/tree/ANCOM-wrapper)
[Working PR](https://github.com/qiime2/q2-composition/pull/88)
