### ISSUE TITLE
ancom: add text wrapping for mouse hover-over in volcano plots

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-composition#51]
**Bug Description**
Hover-over boxes go off-screen and coordinates cannot be viewed.

**References**
[forum xref](https://forum.qiime2.org/t/negative-f-statistic-values-in-ancom-output-after-filtering-low-abundant-taxa/3211?u=nicholas_bokulich)

**Comment by ElDeveloper** [comment]
either that, or including feature metadata.

**Comment by ebolyen** [comment]
@thermokarst has been having some good success with vega, maybe that would be an option here as well?

**Comment by mortonjt** [comment]
That's exciting!  Definitely would like to see those demos at some point.

**Comment by lizgehret** [comment]
Closing all ancom related issues as we will no longer be maintaining/improving ancom, and instead will focus on ancombc improvements moving forward (and ancombc2 once that paper has been published).
