### ISSUE TITLE
Bokeh plot appears to be broken

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-composition#56]
**Description**
The bokeh plots embedded in the viz appear to be broken - the console warning says "`[bokeh] could not set initial ranges`".

**Steps to reproduce the behavior**
1. Open this [example plot](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdocs.qiime2.org%2F2018.6%2Fdata%2Ftutorials%2Fmoving-pictures%2Fancom-Subject.qzv)
2. Open browser's developer console.

**Expected behavior**
The Bokeh plot should be present and not empty. There should be no errors in the dev console.

**Screenshots**
![screen shot 2018-07-17 at 5 59 01 am](https://user-images.githubusercontent.com/274668/42818733-8a08a712-8986-11e8-98f6-964db30c04c9.png)

**Computation Environment**
- OS: Darwin & Linux (example viz above created by Busywork)
- QIIME 2 Release 2018.6

**References**
1. [Original forum post](https://forum.qiime2.org/t/dots-are-missing-the-ancom-plot/5045)
2. [Second forum post](https://forum.qiime2.org/t/bug-bokeh-broken-for-ancom-analysis-visualization/5200)

**Comment by ebolyen** [comment]
Any reason we couldn't turn this into a Vega plot? It think it should work pretty well.

**Comment by thermokarst** [comment]
Good idea! What if this update was rolled into our vega brown-bag luncheon for when @nbokulich is in town?

**Comment by ebolyen** [comment]
I love it!

**Comment by mortonjt** [comment]
In the meantime - do you guys think an appropriate solution would be to recommend users to fix their bokeh version until the next release?

**Comment by ebolyen** [comment]
Yeah that should be fine. And actually, we could probably fix our release environment file the same way manually in the interim.

**Comment by thermokarst** [comment]
PR for pinning the version in the 2018.6 env files: https://github.com/qiime2/environment-files/pull/4

As far as the docs go, I think @ebolyen was planning on rebuilding the 2018.6 docs to include the new copy-to-clipboard commands. If he does that with the patched env, the published visualizations should be back in order.

**Comment by ebolyen** [comment]
Yup, I'll be getting to that in the next day or two.
