### ISSUE TITLE
Update Ancom Plots to Vega 5

### ISSUE THREAD

**Issue by Oddant1** [qiime2/q2-composition#71]
**Bug Description**
Somewhere along the line updates to vega broke our vega visualizations. This includes ancom plots. 

**Comments**
For now it looks like we're going to remove the ability to open them in the vega editor as a band aid, but at some point we'll need to update the plot to work properly with the updated editor.

**Comment by lizgehret** [comment]
Closing all ancom related issues as we will no longer be maintaining/improving ancom, and instead will focus on ancombc improvements moving forward (and ancombc2 once that paper has been published).
