### ISSUE TITLE
Upgrade to ANCOM-BC

### ISSUE THREAD

**Issue by jwdebelius** [qiime2/q2-composition#76]
**Improvement Description**
I think rather than upgrading from ANCOM, it might make sense to upgrade to ANCOM-BC, although I'm open to both. Having been through the ANCOM-BC paper once, I think it will be the next big method and its worth figuring out how to integrate it in qiime2. 

**Current Behavior**
Currently, qiime2 uses the scikit-bio implementation of ANCOM I with a pseudocount of 1

**Proposed Behavior**
An Implementation of ANCOM-BC separating out the zero substitution step and introducing the statistical test. I'd love to see the test separated from visualization and/or the ability to extract the full results table programatically. (Actually, this is a behavior I'd like to see on a lot of the visualizers).

**References**
This is semi an update/response to #48. I think @mortonjt mentioned at one point that he was interested if he could figure out the table transformation, but I'm happy to collaborate on it

**Comment by ebolyen** [comment]
I have some great news then, @mortonjt is already on the case! https://github.com/mortonjt/q2-ancombc

**Comment by mortonjt** [comment]
We have the ANCOM-BC plugin already sketched out here : https://github.com/mortonjt/q2-ancombc
So feel free to check it out - it runs, but the documentation needs some work (support with that would be very helpful).

There are a couple of notable differences between ANCOM and ANCOM-BC, namely ANCOM-BC does return log-fold changes whereas ANCOM doesn't.  In the q2-ANCOMBC plugin, the method returns a differential type.  Ideally, we would have the volcano plots that would be decoupled that can also accept a differential type as input (that way ANCOM-BC would be also compatible with qurro).

**Comment by jwdebelius** [comment]
Should I then close this issue?

 I'd love to see ANCOM decoupled, which is pretty simple here... although I think the other question for users is where differential plots should go. Personally, from where I sit in the user/developer continuum, I'd rather they be in a plugin that gets installed automatically, mostly because remembering and managing plugin installation can be a challenge if installations are shared across systems or there are weird update issues?

**Comment by mortonjt** [comment]
Thoughts @ebolyen @thermokarst ? I'm not opposed to ANCOM-BC being in the core distribution, but also note that this is still a rapidly developing ecosystem. One possibility is to aggregate multiple statistical tools (i.e. qurro, deicode, CTF, mmvec ...) into a single environment.yml and sync their dependencies with qiime2.

**Comment by jwdebelius** [comment]
If that happens, can we (you) also re-do the gneiss tutorial for songbird or some alternative? I went to run Gneiss for reasons<sup>TM<sup> (mostly because I'm trying to teach ILR and I have a dataset where ILR makes potential sense) and there's not much left in that plugin that's useful. ...Although I guess that means a major refactor of songbird for python 3.8 and pandas 1 which is another issue :)

**Comment by mortonjt** [comment]
Yes, that is also on the way.  See
https://github.com/knightlab-analyses/empress-analyses/pull/16

**Comment by lizgehret** [comment]
Hey @jwdebelius and @mortonjt ! I am currently working on an ANCOM-BC wrapper for [Huang's R package](https://github.com/FrederickHuangLin/ANCOMBC/tree/RELEASE_3_15), which you can view progress on in [this branch](https://github.com/qiime2/q2-composition/tree/ANCOM-wrapper), and this [working PR](https://github.com/qiime2/q2-composition/pull/88).

I'm anticipating that this should be completed and ready for the November 2022 release, so I'm going to close out your PR @jwdebelius and you are both welcome to follow progress on this at the above locations. Let me know if you have any questions! 🙂
