### ISSUE TITLE
The F-score appears to be missing

### ISSUE THREAD

**Issue by mortonjt** [qiime2/q2-composition#77]
**Bug Description**

In this [post](https://forum.qiime2.org/t/ancom-parameters-and-interpreting-output/19945), it appears that the F-score was replaced by clr, but the x label doesn't suggest this.  If the F-test is going to be used, the F-score should be clearly labeled in the x-axis

**Comment by lizgehret** [comment]
Closing all ancom related issues as we will no longer be maintaining/improving ancom, and instead will focus on ancombc improvements moving forward (and ancombc2 once that paper has been published).
