### ISSUE TITLE
Order of each group value in metadata randomly changed when rerun ancom

### ISSUE THREAD

**Issue by satopan** [qiime2/q2-composition#83]
## Bug Description

The order of each group value in metadata randomly changed when rerun ancom.
As a result, the positive and negative of the clr values were randomly reversed.

- https://github.com/qiime2/q2-composition/blob/462cdd057e9f5e0a872f71f70d2bc988c8f0c353/q2_composition/_ancom.py#L71

## Expected behavior
This order of group values should be reorder axis by first unique appearance of each group value in metadata.
As a result, the positive and negative of the clr values shoud be consistent when rerun ancom.

- https://github.com/qiime2/q2-feature-table/blob/90b75bb4848371bd640fe7c4baf14bc448d597c9/q2_feature_table/_group.py#L59

**Comment by lizgehret** [comment]
Closing all ancom related issues as we will no longer be maintaining/improving ancom, and instead will focus on ancombc improvements moving forward (and ancombc2 once that paper has been published).
